---
version: '3'
services:
  # [Install Elasticsearch with Docker | Elasticsearch Guide [7.2] | Elastic](https://www.elastic.co/guide/en/elasticsearch/reference/7.2/docker.html)
  elasticsearch:
    image: elasticsearch:7.2.1
    ports:
      - 9200:9200 # サービス用のポート
      - 9300:9300 # ノード間通信のためのポート
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - XPACK_SECURITY_ENABLED=true # X-Pack の有効化（パスワード有効化）
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
  kibana:
    image: kibana:7.2.1
    ports:
      - 5601:5601
    environment:
      # Kibana が起動時に Elasticsearch へ接続するための認証情報をセット
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
    depends_on:
      - elasticsearch
volumes:
  esdata:
    driver: local